// SOA ISO/IEC 27701:2025 — SGDP-UPS 2026
// 27 controles · Incluye B.1.2.6, B.1.2.7 e ISO/IEC 42001 (Guía SPDP V2)
// Base: EIPD_Calculador_UPS_v3.xlsx + Guía SPDP Edición 2 (2026)

var SOA_DATA = [
  {id:'A.1.2.2', desc:'Identificar y documentar propósito del tratamiento', just:'Art. 6 lit.b) LOPDP + Art. 24 lit.c)', estado:'En implementación', prio:'CRÍTICA', resp:'Gestora PDP / DTIC', plazo:'Q2 2026', acciones:'Completar RAT 226 procedimientos Fase 9 · Validar con Data Owners'},
  {id:'A.1.2.3', desc:'Identificar base legal de cada tratamiento', just:'Art. 11 LOPDP — bases de licitud', estado:'En implementación', prio:'CRÍTICA', resp:'Gestora PDP', plazo:'Q2 2026', acciones:'Matriz de licitud por tipo de tratamiento'},
  {id:'A.1.2.4', desc:'Determinar cuándo obtener consentimiento', just:'Art. 12 LOPDP', estado:'No implementado', prio:'ALTA', resp:'DTIC / Gestora PDP', plazo:'Q3 2026', acciones:'Diseñar flujos de consentimiento por canal'},
  {id:'A.1.2.5', desc:'Obtener y registrar consentimiento del titular', just:'Art. 12 y 47 LOPDP', estado:'No implementado', prio:'ALTA', resp:'DTIC', plazo:'Q3 2026', acciones:'Módulo gestión consentimientos en SIGA'},
  {id:'A.1.2.6', desc:'Evaluación de impacto (DPIA / EIPD)', just:'Art. 44-45 LOPDP', estado:'Parcialmente implementado', prio:'CRÍTICA', resp:'Gestora PDP', plazo:'Q2 2026', acciones:'Metodología DPIA UPS · 5 EIPDs piloto en curso'},
  {id:'A.1.2.7', desc:'Contratos con encargados del tratamiento (DPA)', just:'Art. 10 LOPDP', estado:'Parcialmente implementado', prio:'CRÍTICA', resp:'Procuraduría / Gestora PDP', plazo:'Q2 2026', acciones:'Clausulado modelo · Inventario encargados activos (CEDIA, ZHM, EXPRESSALL)'},
  {id:'A.1.2.8', desc:'Corresponsabilidad / Controlador conjunto', just:'Convenios movilidad e investigación', estado:'No implementado', prio:'MEDIA', resp:'Procuraduría', plazo:'Q3 2026', acciones:'Identificar convenios con corresponsabilidad'},
  {id:'A.1.2.9', desc:'Registros de actividades de tratamiento (RAT)', just:'Art. 48 LOPDP', estado:'En implementación', prio:'CRÍTICA', resp:'Gestora PDP', plazo:'Q2 2026', acciones:'RAT 2026 en desarrollo · Sistema SGDP'},
  {id:'A.1.3.2', desc:'Cumplir obligaciones con titulares (derechos ARCO+)', just:'Arts. 24-33 LOPDP', estado:'En implementación', prio:'CRÍTICA', resp:'Gestora PDP', plazo:'Q2 2026', acciones:'PDP-PRO-001 implementado · Notificación brechas'},
  {id:'A.1.3.3', desc:'Determinar información a proporcionar al titular', just:'Art. 24 LOPDP — aviso de privacidad', estado:'En implementación', prio:'CRÍTICA', resp:'Gestora PDP / DTIC', plazo:'Q2 2026', acciones:'7 templates avisos por grupo de titulares'},
  {id:'A.1.3.4', desc:'Proporcionar información a titulares (capa 1 y 2)', just:'Art. 25 LOPDP', estado:'Parcialmente implementado', prio:'ALTA', resp:'Gestora PDP / DTIC', plazo:'Q2 2026', acciones:'Publicar avisos web · Integrar en formularios'},
  {id:'A.1.3.5', desc:'Modificar o retirar el consentimiento', just:'Art. 12 LOPDP', estado:'No implementado', prio:'ALTA', resp:'DTIC', plazo:'Q3 2026', acciones:'Portal autogestión · Botón retirar consentimiento'},
  {id:'A.1.3.6', desc:'Oponerse al procesamiento de datos personales', just:'Art. 29 LOPDP', estado:'No implementado', prio:'ALTA', resp:'Gestora PDP', plazo:'Q3 2026', acciones:'Formulario oposición en portal ARCO+'},
  {id:'A.1.3.7', desc:'Derechos ARCO+ (acceso, rectificación, cancelación, oposición)', just:'Arts. 30-32 LOPDP · 15 días hábiles', estado:'Parcialmente implementado', prio:'CRÍTICA', resp:'Gestora PDP', plazo:'Q2 2026', acciones:'Procedimiento ARCO V2 · Formularios estandarizados'},
  {id:'A.1.3.8', desc:'Informar cambios de tratamiento a terceros', just:'Art. 31-32 LOPDP', estado:'No implementado', prio:'MEDIA', resp:'Gestora PDP', plazo:'Q3 2026', acciones:'Módulo destinatarios en RAT'},
  {id:'A.1.3.9', desc:'Proporcionar copia de datos — portabilidad', just:'Art. 33 LOPDP', estado:'No implementado', prio:'ALTA', resp:'DTIC', plazo:'Q3 2026', acciones:'Formatos CSV/JSON · Funcionalidad SIGA'},
  {id:'A.1.3.10',desc:'Manejo completo de solicitudes ARCO+', just:'Art. 30-33 LOPDP', estado:'En implementación', prio:'CRÍTICA', resp:'Gestora PDP', plazo:'Q2 2026', acciones:'Procedimiento completo · Plazos 15 días hábiles'},
  {id:'A.1.4.2', desc:'Limitar recopilación de datos (minimización)', just:'Art. 6 lit.c) LOPDP', estado:'Parcialmente implementado', prio:'ALTA', resp:'DTIC / Gestora PDP', plazo:'Q2 2026', acciones:'Auditoría formularios admisión/matrícula'},
  {id:'A.1.4.3', desc:'Limitar el procesamiento — finalidad', just:'Art. 6 lit.b) LOPDP', estado:'Parcialmente implementado', prio:'ALTA', resp:'DTIC / Gestora PDP', plazo:'Q2 2026', acciones:'Matriz de acceso por rol · Revisión trimestral'},
  {id:'A.1.4.8', desc:'Retención y conservación de datos personales', just:'Art. 6 lit.e) LOPDP', estado:'En implementación', prio:'CRÍTICA', resp:'DTIC / Gestora PDP', plazo:'Q2 2026', acciones:'Política retención 2026 · Tablas de retención por tipo de dato'},
  {id:'A.1.4.10',desc:'Controles de transmisión — cifrado en tránsito', just:'Art. 48 LOPDP + ISO 27001 A.8.24', estado:'Parcialmente implementado', prio:'CRÍTICA', resp:'DTIC', plazo:'Q2 2026', acciones:'Migración HTTPS · Política cifrado TLS 1.3 en todos los sistemas'},
  {id:'A.1.5.2', desc:'Base legal para transferencias internacionales', just:'Art. 11 y 34 LOPDP', estado:'En implementación', prio:'CRÍTICA', resp:'Procuraduría / Gestora PDP', plazo:'Q2 2026', acciones:'Inventario transferencias · Análisis base legal por proveedor'},
  {id:'A.1.5.3', desc:'Países y organizaciones destino de transferencias', just:'Art. 34-37 LOPDP', estado:'En implementación', prio:'CRÍTICA', resp:'Procuraduría / Gestora PDP', plazo:'Q2 2026', acciones:'Inventario cloud extranjero (BestKloud USA, UNED España) · Cláusulas estándar'},
  {id:'A.1.5.4', desc:'Registros y trazabilidad de transferencias', just:'Art. 48 LOPDP', estado:'No implementado', prio:'ALTA', resp:'DTIC / Gestora PDP', plazo:'Q3 2026', acciones:'Módulo registro transferencias en SGDP'},
  {id:'B.1.2.6', desc:'DPIA como control de seguridad continuo — semestral', just:'Art. 42 LOPDP + Guía SPDP V2 #30', estado:'En implementación', prio:'CRÍTICA', resp:'Gestora PDP', plazo:'Q2 2026', acciones:'EIPD recurrente semestral · Documentar como control activo en SGDP', nuevo:true},
  {id:'B.1.2.7', desc:'Criptografía obligatoria vinculada al Art. 37 LOPDP', just:'Art. 37 LOPDP + Guía SPDP V2 #31', estado:'No implementado', prio:'CRÍTICA', resp:'DTIC', plazo:'Q2 2026', acciones:'Inventariar herramientas de cifrado SIGA, ATENEA, servidores · Documentar formalmente', nuevo:true},
  {id:'ISO/IEC 42001', desc:'Gestión de riesgos para sistemas de Inteligencia Artificial', just:'Art. 20 LOPDP + Guía SPDP V2 #12', estado:'No implementado', prio:'ALTA', resp:'DTIC / Gestora PDP', plazo:'Q3 2026', acciones:'Política uso ético IA · DPIA para ATENEA y sistema de proctoring', nuevo:true}
];
